config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :comments, except: [:new, :index, :create]
  post '/comments/:comment_id', to: 'comments#create_comment', as: "comment_create"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :post

  belongs_to(
    :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )

  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.post_id = params[:post_id]
    if comment.save
      redirect_to post_url(comment.post_id)
    else
      flash.now[:error] = ["Comment could not be created!"]
      render :new
    end
  end

  def create_comment
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.parent_comment_id = params[:id]
    if comment.save
      redirect_to post_url(comment.post_id)
    else
      flash.now[:error] = ["Comment could not be created!"]
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    render :edit
  end

  def update
    comment = Comment.find(params[:id])
    if comment.update_attributes(comment_params)
      redirect_to post_url(comment.post_id)
    else
      flash.now[:errors] = ["Comment was not updated!"]
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/new.html.erb
<h1>Create a comment</h1>
<form action="<%= post_comments_url(params[:post_id])%>" method="POST">
  <%= auth_token %>
  <textarea rows="8" cols="40" name="comment[content]"></textarea>
  <input type="submit" value="Submit">
</form>

app/views/comments/show.html.erb
<h1>show page for comment</h1>

<form action="<%=post_comments_url(params[:id])%>" method="POST">
  <%= auth_token %>
  <label>Reply to this comment
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>
  <input type="submit"  value="Submit">
</form>