config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :comments, except: [:new, :index, :create]
  post '/comments/:comment_id', to: 'comments#create_comment', as: "comment_create"

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )

  has_many(
    :post_subs,
    class_name: "PostSub",
    foreign_key: :sub_id,
    primary_key: :id,
    inverse_of: :sub
  )

  has_many(
    :posts,
    through: :post_subs,
    source: :post
  )

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    subreddit = Sub.new(sub_params)
    subreddit.moderator_id = current_user.id
    if subreddit.save
      redirect_to subs_url
    else
      flash.now[:errors] = ["Sub wasn't created!"]
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    subreddit = Sub.find(params[:id])
    if subreddit.update_attributes(sub_params)
      redirect_to sub_url(subreddit.id)
    else
      flash.now[:errors] = ["Sub was not updated!"]
      render :edit
    end
  end

  def destroy
    subreddit = Sub.find(params[:id])
    if subreddit.destroy
      flash[:notice] = ["Subreddit was destroyed!"]
      redirect_to subs_url
    else
      flash[:errors] = ["Subreddit was not destroyed."]
      redirect_to sub_url(subreddit.id)
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, post_ids: [])
  end
end

app/views/subs/index.html.erb
<ul>
  <% @subs.each do |subreddit| %>
    <li> <a href="<%= sub_url(subreddit.id) %>"><%= subreddit.title %></a></li>
    <br>
  <% end %>
</ul>

<hr>

<p>
  <a href="<%= new_sub_url %>">Create New Subreddit</a>
</p>

app/views/subs/new.html.erb
<h1> Create Subreddit</h1>

<form action="<%=subs_url %>" method="POST">
  <%= auth_token %>
  <label>Title:
    <input type="text" name="sub[title]">
  </label>
  <br><br>
  <label>Description:
    <textarea cols="40" rows="5" name="sub[description]"></textarea>
  </label>
  <br><br>
  <input type="submit" value="Submit">
</form>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<ul>
  <% @sub.posts.each do |post| %>
    <h3><li> <a href="<%= post_url(post.id) %>"> <%= post.title %> </a></li></h3>
    <h5> <%= post.created_at %> by <%= post.author.username %> </h5>
    <% if current_user && (current_user.id == post.author_id) %>
      <a href="<%= edit_post_url %>">Edit post</a>
    <% end %>
  <% end %>
</ul>

<a href="<%= new_sub_post_url(@sub.id) %>">Create new post</a>

<br><br>
<a href="<%= subs_url %> ">Return to front page</a>