config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :comments, except: [:new, :index, :create]
  post '/comments/:comment_id', to: 'comments#create_comment', as: "comment_create"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true

  has_many :comments

  belongs_to(
    :subreddit,
    class_name: "Sub",
    foreign_key: :sub_id,
    primary_key: :id
  )
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many(
    :post_subs,
    class_name: "PostSub",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post
  )

  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @subs = Sub.all
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    post = Post.new(post_params)
    post.author_id = current_user.id
    post.sub_ids = params[:post][:sub_ids]
    if post.save
      redirect_to sub_url(params[:sub_id])
    else
      flash.now[:errors] = ["Post could not be created"]
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    render :edit
  end

  def update
    post = Post.find(params[:id])
    post.sub_ids = params[:post][:sub_ids]
    if post.update_attributes(post_params)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Post could not be edited!"]
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = ["Post was successfully destroyed!"]
      redirect_to sub_url(params[:sub_id])
    else
      flash[:errors] = ["Post was not deleted!"]
      redirect_to sub_url(params[:sub_id])
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, sub_ids: [])
  end
end

app/views/posts/_form.html.erb
<% action = @post.persisted? ? post_url(@post.id) : sub_posts_url(params[:sub_id]) %>
<% method = @post.persisted? ? "PATCH" : "POST" %>


<form action="<%= action %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>"
  <%= auth_token %>
  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br><br>

  <label>Content:
    <textarea name="post[content]"><%= @post.content %></textarea>
  </label>

  <br><br>

  <% @subs.each do |subreddit| %>
    <label><%= subreddit.title %>
    <input type="checkbox" name="post[sub_ids][]" value=" <%= subreddit.id %>"
    <%= "checked" if @post.sub_ids.include?(subreddit.id) %> >
    </label>
  <% end %>

  <input type="submit" value="Submit">

</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %> by <%= @post.author.username %> </h1>

<p>
  <%= @post.content %>
</p>

<a href="<%= new_post_comment_url(@post.id) %>">Reply</a>

<h3>Comments</h3>
<ul>
 <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
  <p><li> <a href="<%= comment_create_url(comment.id) %>"><%= comment.content %></a> </li>
  <font size ="2">Posted by:<%= comment.author.username %> at <%= comment.created_at %></font>
    <ul>
      <% comment.child_comments.each do |child| %>
        <li> <%= child.content %> </li>
      <% end %>
    </ul>
 <% end %></p>
</ul>

<% @subs.each do |subreddit| %>
  <a href="<%= sub_url(subreddit.id) %>">Go to <%= subreddit.title %> </a>
  <br>
<% end %>